project:
  type: website

website:
  title: "new-book"
  navbar:
    left:
      - href: index.ipynb
        text: Home
      - about.ipynb

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
