project:
  type: website
  output-dir: _site

website:
  title: "데이터 사이언스 스쿨"
  favicon: logo.png
  search: false
  navbar:
    background: "#ecf0f1"
    foreground: black
    logo: logo.png
    left:
      - index.ipynb
      - about.ipynb
      - notebook.ipynb
  sidebar:
    style: "docked"
    search: true
    contents: auto

format:
  html:
    lang: ko
    theme: flatly
    mainfont: "Noto Sans KR"
    monofont: "Nanum Gothic Coding"
    fontsize: small-medium
    css: styles.css
    toc: true
    code-fold: false
    html-math-method: katex
    title-block-style: none
  pdf:
    geometry:
      - top=30mm
      - left=30mm
    include-in-header:
      text: |
        \usepackage{pdfpages}
        \usepackage{kotex}
    mainfont: "NanumMyeongjo"
    sansfont: "NanumGothic"
    monofont: "D2Coding"
